apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate
  namespace: famio-prod
spec:
  args:
  - name: service-name
  metrics:
  - name: success-rate
    interval: 5m
    successCondition: result[0] >= 0.95
    provider:
      prometheus:
        address: http://prometheus.monitoring.svc.cluster.local:9090
        query: |
          sum(rate(http_request_duration_seconds_count{job="famio", status!~"5.*"}[5m])) / 
          sum(rate(http_request_duration_seconds_count{job="famio"}[5m]))
