apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: famio-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/iChancetek/WeAreFamily---Social-Media-Platform.git'
    targetRevision: HEAD
    path: infrastructure/helm/famio
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: replicaCount
          value: '3'
        - name: ingress.enabled
          value: 'true'
        - name: ingress.hosts[0].host
          value: 'famio.us'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: famio-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
