
import { Metadata } from 'next';
import { isUrlVideo, extractYouTubeId, fetchYouTubeTitle } from '@/lib/media-utils';

// Default Fallback Image (Must be generic, not user-specific)
const OG_IMAGE_DEFAULT = "https://firebasestorage.googleapis.com/v0/b/we-are-family-221.appspot.com/o/admin%2Ffamio-og-default.png?alt=media";
// Note: If this URL doesn't exist, we might need a placeholder. 
// For now, I'll use a reliable placeholder or the user needs to provide one.
// Let's use a nice generated one if the specific file isn't guaranteed.
const OG_IMAGE_FALLBACK = "https://placehold.co/1200x630/1e293b/ffffff/png?text=Famio+Content";

type PostData = {
    content?: string;
    mediaUrls?: string[];
    thumbnailUrl?: string | null; // Added
    author?: {
        displayName?: string;
    };
};

export async function generateContentMetadata(
    post: PostData,
    canonicalUrl: string,
    embedUrl?: string
): Promise<Metadata> {

    // 1. YouTube Logic
    const youtubeUrlMatch = post.content?.match(/https?:\/\/(www\.)?(youtube\.com|youtu\.be)\/\S+/gi);
    const youtubeUrl = youtubeUrlMatch ? youtubeUrlMatch[0].replace(/[\s.,!?;:]+$/, '').trim() : null;

    let videoTitle = null;
    if (youtubeUrl) {
        const yId = extractYouTubeId(youtubeUrl);
        if (yId) {
            videoTitle = await fetchYouTubeTitle(yId);
        }
    }

    // Title Logic
    const authorName = post.author?.displayName || "Famio User";
    const title = videoTitle || (post.content ? truncate(post.content, 60) : `${authorName} on Famio`);

    // Description Logic: Strip URLs to avoid ugly links in preview
    const cleanContent = post.content ? post.content.replace(/(?:https?|ftp):\/\/[\n\S]+/g, '').trim() : '';
    const description = cleanContent
        ? truncate(cleanContent, 160)
        : (videoTitle ? `Watch "${videoTitle}" on Famio` : `View this post on Famio.`);


    // 2. Image Selection Logic (STRICT: NO PROFILE PHOTOS)
    let imageUrl = OG_IMAGE_FALLBACK;
    let type = 'article';
    let videoUrlForOg: string | undefined = undefined;

    // Priority 1: YouTube
    if (youtubeUrl) {
        const yId = extractYouTubeId(youtubeUrl);
        if (yId) {
            imageUrl = `https://img.youtube.com/vi/${yId}/maxresdefault.jpg`;
            type = 'video.other';
            videoUrlForOg = youtubeUrl;
        }
    }
    // Priority 2: Explicit Thumbnail (Uploaded Video)
    else if (post.thumbnailUrl) {
        imageUrl = post.thumbnailUrl;
        // Check if underlying media is video to set correct OG type
        if (post.mediaUrls && post.mediaUrls.length > 0 && isUrlVideo(post.mediaUrls[0])) {
            type = 'video.other';
            videoUrlForOg = post.mediaUrls[0];
        }
    }
    // Priority 3: Uploaded Media (Photo/Video Fallback)
    else if (post.mediaUrls && post.mediaUrls.length > 0) {
        const firstMedia = post.mediaUrls[0];

        if (isUrlVideo(firstMedia)) {
            // Video without generic thumbnail -> Use Placeholder
            // Note: If we had a thumbnail generated by cloud function, we would use it here.
            imageUrl = "https://placehold.co/1200x630/000000/ffffff/png?text=▶+Watch+Video";
            type = 'video.other';
            videoUrlForOg = firstMedia;
        } else {
            // Photo -> Use directly
            imageUrl = firstMedia;
        }
    }

    return {
        title,
        description,
        openGraph: {
            title,
            description,
            type: type as any,
            url: canonicalUrl,
            siteName: 'Famio',
            locale: 'en_US',
            images: [
                {
                    url: imageUrl,
                    width: 1200,
                    height: 630,
                    alt: title,
                    type: 'image/jpeg'
                }
            ],
            videos: videoUrlForOg ? [{ url: videoUrlForOg }] : undefined,
            // Additional metadata for better SEO
            ...(post.author?.displayName && {
                article: {
                    authors: [post.author.displayName],
                    publishedTime: new Date().toISOString(),
                }
            })
        },
        twitter: {
            card: 'summary_large_image',
            title,
            description,
            images: [imageUrl],
            site: '@Famio',
            creator: post.author?.displayName ? `@${post.author.displayName.replace(/\s+/g, '')}` : '@Famio'
        },
        // Additional tags for rich previews
        metadataBase: new URL(canonicalUrl.split('/post/')[0]),
        alternates: {
            canonical: canonicalUrl
        },
        robots: {
            index: true,
            follow: true,
            googleBot: {
                index: true,
                follow: true,
                'max-image-preview': 'large',
                'max-snippet': -1
            }
        }
    };
}

function truncate(str: string, n: number) {
    return (str.length > n) ? str.slice(0, n - 1) + '...' : str;
}
